# Generated by Django 3.0.2 on 2020-01-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='last update')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='NO_NAME', max_length=1000, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.CharField(max_length=200, verbose_name='diet'),
        ),
        migrations.AlterField(
            model_name='food',
            name='brand',
            field=models.CharField(max_length=200, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fda_guidelines',
            field=models.BooleanField(verbose_name='adheres to FDA guidelines'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_form',
            field=models.CharField(max_length=200, null=True, verbose_name='food form'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.CharField(max_length=4096, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='item number'),
        ),
        migrations.AlterField(
            model_name='food',
            name='lg_breed',
            field=models.BooleanField(verbose_name='large breeds'),
        ),
        migrations.AlterField(
            model_name='food',
            name='lifestage',
            field=models.CharField(max_length=200, null=True, verbose_name='lifestage'),
        ),
        migrations.AlterField(
            model_name='food',
            name='md_breed',
            field=models.BooleanField(verbose_name='medium breeds'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sm_breed',
            field=models.BooleanField(verbose_name='small breeds'),
        ),
        migrations.AlterField(
            model_name='food',
            name='xlg_breed',
            field=models.BooleanField(verbose_name='giant breeds'),
        ),
        migrations.AlterField(
            model_name='food',
            name='xsm_breed',
            field=models.BooleanField(verbose_name='extra small & toy breeds'),
        ),
    ]
