# Generated by Django 3.0.2 on 2020-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food_search', '0002_auto_20200116_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperupdates',
            name='count',
            field=models.IntegerField(default=3589, verbose_name='food count'),
            preserve_default=False,
        ),
    ]
